import type { Metadata } from "next";
import localFont from "next/font/local";
import { Roboto_Slab } from 'next/font/google'
import "./globals.scss";

const enchantedTales = localFont({
  src: "./fonts/EnchantedTales.otf",
  variable: "--enchanted",
});
const robotoSlab = Roboto_Slab({
  variable: "--roboto-slab",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${enchantedTales.variable} ${robotoSlab.variable}`}>
        {children}
      </body>
    </html>
  );
}
